/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppQueueRouteImport } from './routes/_app.queue'
import { Route as AppOverdueRouteImport } from './routes/_app.overdue'
import { Route as AppOrdersRouteImport } from './routes/_app.orders'
import { Route as AppHelpRouteImport } from './routes/_app.help'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'
import { Route as AppActivationKeysRouteImport } from './routes/_app.activation-keys'
import { Route as AppAccountRouteImport } from './routes/_app.account'
import { Route as AppStoreIndexRouteImport } from './routes/_app.store.index'
import { Route as AppStoreIdRouteImport } from './routes/_app.store.$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppQueueRoute = AppQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AppRoute,
} as any)
const AppOverdueRoute = AppOverdueRouteImport.update({
  id: '/overdue',
  path: '/overdue',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpRoute = AppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppActivationKeysRoute = AppActivationKeysRouteImport.update({
  id: '/activation-keys',
  path: '/activation-keys',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppStoreIndexRoute = AppStoreIndexRouteImport.update({
  id: '/store/',
  path: '/store/',
  getParentRoute: () => AppRoute,
} as any)
const AppStoreIdRoute = AppStoreIdRouteImport.update({
  id: '/store/$id',
  path: '/store/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/account': typeof AppAccountRoute
  '/activation-keys': typeof AppActivationKeysRoute
  '/analytics': typeof AppAnalyticsRoute
  '/dashboard': typeof AppDashboardRoute
  '/help': typeof AppHelpRoute
  '/orders': typeof AppOrdersRoute
  '/overdue': typeof AppOverdueRoute
  '/queue': typeof AppQueueRoute
  '/settings': typeof AppSettingsRoute
  '/store/$id': typeof AppStoreIdRoute
  '/store/': typeof AppStoreIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/account': typeof AppAccountRoute
  '/activation-keys': typeof AppActivationKeysRoute
  '/analytics': typeof AppAnalyticsRoute
  '/dashboard': typeof AppDashboardRoute
  '/help': typeof AppHelpRoute
  '/orders': typeof AppOrdersRoute
  '/overdue': typeof AppOverdueRoute
  '/queue': typeof AppQueueRoute
  '/settings': typeof AppSettingsRoute
  '/store/$id': typeof AppStoreIdRoute
  '/store': typeof AppStoreIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/register': typeof RegisterRoute
  '/_app/account': typeof AppAccountRoute
  '/_app/activation-keys': typeof AppActivationKeysRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/help': typeof AppHelpRoute
  '/_app/orders': typeof AppOrdersRoute
  '/_app/overdue': typeof AppOverdueRoute
  '/_app/queue': typeof AppQueueRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/store/$id': typeof AppStoreIdRoute
  '/_app/store/': typeof AppStoreIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/register'
    | '/account'
    | '/activation-keys'
    | '/analytics'
    | '/dashboard'
    | '/help'
    | '/orders'
    | '/overdue'
    | '/queue'
    | '/settings'
    | '/store/$id'
    | '/store/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/register'
    | '/account'
    | '/activation-keys'
    | '/analytics'
    | '/dashboard'
    | '/help'
    | '/orders'
    | '/overdue'
    | '/queue'
    | '/settings'
    | '/store/$id'
    | '/store'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/register'
    | '/_app/account'
    | '/_app/activation-keys'
    | '/_app/analytics'
    | '/_app/dashboard'
    | '/_app/help'
    | '/_app/orders'
    | '/_app/overdue'
    | '/_app/queue'
    | '/_app/settings'
    | '/_app/store/$id'
    | '/_app/store/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/queue': {
      id: '/_app/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof AppQueueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/overdue': {
      id: '/_app/overdue'
      path: '/overdue'
      fullPath: '/overdue'
      preLoaderRoute: typeof AppOverdueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders': {
      id: '/_app/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/help': {
      id: '/_app/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AppHelpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/activation-keys': {
      id: '/_app/activation-keys'
      path: '/activation-keys'
      fullPath: '/activation-keys'
      preLoaderRoute: typeof AppActivationKeysRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/store/': {
      id: '/_app/store/'
      path: '/store'
      fullPath: '/store/'
      preLoaderRoute: typeof AppStoreIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/store/$id': {
      id: '/_app/store/$id'
      path: '/store/$id'
      fullPath: '/store/$id'
      preLoaderRoute: typeof AppStoreIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppActivationKeysRoute: typeof AppActivationKeysRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppHelpRoute: typeof AppHelpRoute
  AppOrdersRoute: typeof AppOrdersRoute
  AppOverdueRoute: typeof AppOverdueRoute
  AppQueueRoute: typeof AppQueueRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStoreIdRoute: typeof AppStoreIdRoute
  AppStoreIndexRoute: typeof AppStoreIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppActivationKeysRoute: AppActivationKeysRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppHelpRoute: AppHelpRoute,
  AppOrdersRoute: AppOrdersRoute,
  AppOverdueRoute: AppOverdueRoute,
  AppQueueRoute: AppQueueRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStoreIdRoute: AppStoreIdRoute,
  AppStoreIndexRoute: AppStoreIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
