/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuperRouteImport } from './routes/super'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperIndexRouteImport } from './routes/super.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SuperStationsRouteImport } from './routes/super.stations'
import { Route as SuperNotificationsRouteImport } from './routes/super.notifications'
import { Route as SuperInsightsRouteImport } from './routes/super.insights'
import { Route as SuperChatRouteImport } from './routes/super.chat'
import { Route as SuperBroadcastRouteImport } from './routes/super.broadcast'
import { Route as SuperAdminsRouteImport } from './routes/super.admins'
import { Route as AdminStationRouteImport } from './routes/admin.station'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminMembersRouteImport } from './routes/admin.members'
import { Route as AdminLockersRouteImport } from './routes/admin.lockers'
import { Route as AdminChatRouteImport } from './routes/admin.chat'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'

const SuperRoute = SuperRouteImport.update({
  id: '/super',
  path: '/super',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperIndexRoute = SuperIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SuperStationsRoute = SuperStationsRouteImport.update({
  id: '/stations',
  path: '/stations',
  getParentRoute: () => SuperRoute,
} as any)
const SuperNotificationsRoute = SuperNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SuperRoute,
} as any)
const SuperInsightsRoute = SuperInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => SuperRoute,
} as any)
const SuperChatRoute = SuperChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => SuperRoute,
} as any)
const SuperBroadcastRoute = SuperBroadcastRouteImport.update({
  id: '/broadcast',
  path: '/broadcast',
  getParentRoute: () => SuperRoute,
} as any)
const SuperAdminsRoute = SuperAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => SuperRoute,
} as any)
const AdminStationRoute = AdminStationRouteImport.update({
  id: '/station',
  path: '/station',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLockersRoute = AdminLockersRouteImport.update({
  id: '/lockers',
  path: '/lockers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChatRoute = AdminChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/super': typeof SuperRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/lockers': typeof AdminLockersRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/station': typeof AdminStationRoute
  '/super/admins': typeof SuperAdminsRoute
  '/super/broadcast': typeof SuperBroadcastRoute
  '/super/chat': typeof SuperChatRoute
  '/super/insights': typeof SuperInsightsRoute
  '/super/notifications': typeof SuperNotificationsRoute
  '/super/stations': typeof SuperStationsRoute
  '/admin/': typeof AdminIndexRoute
  '/super/': typeof SuperIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/lockers': typeof AdminLockersRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/station': typeof AdminStationRoute
  '/super/admins': typeof SuperAdminsRoute
  '/super/broadcast': typeof SuperBroadcastRoute
  '/super/chat': typeof SuperChatRoute
  '/super/insights': typeof SuperInsightsRoute
  '/super/notifications': typeof SuperNotificationsRoute
  '/super/stations': typeof SuperStationsRoute
  '/admin': typeof AdminIndexRoute
  '/super': typeof SuperIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/super': typeof SuperRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/lockers': typeof AdminLockersRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/station': typeof AdminStationRoute
  '/super/admins': typeof SuperAdminsRoute
  '/super/broadcast': typeof SuperBroadcastRoute
  '/super/chat': typeof SuperChatRoute
  '/super/insights': typeof SuperInsightsRoute
  '/super/notifications': typeof SuperNotificationsRoute
  '/super/stations': typeof SuperStationsRoute
  '/admin/': typeof AdminIndexRoute
  '/super/': typeof SuperIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/signup'
    | '/super'
    | '/admin/analytics'
    | '/admin/chat'
    | '/admin/lockers'
    | '/admin/members'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/station'
    | '/super/admins'
    | '/super/broadcast'
    | '/super/chat'
    | '/super/insights'
    | '/super/notifications'
    | '/super/stations'
    | '/admin/'
    | '/super/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/admin/analytics'
    | '/admin/chat'
    | '/admin/lockers'
    | '/admin/members'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/station'
    | '/super/admins'
    | '/super/broadcast'
    | '/super/chat'
    | '/super/insights'
    | '/super/notifications'
    | '/super/stations'
    | '/admin'
    | '/super'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/signup'
    | '/super'
    | '/admin/analytics'
    | '/admin/chat'
    | '/admin/lockers'
    | '/admin/members'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/station'
    | '/super/admins'
    | '/super/broadcast'
    | '/super/chat'
    | '/super/insights'
    | '/super/notifications'
    | '/super/stations'
    | '/admin/'
    | '/super/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  SuperRoute: typeof SuperRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/super': {
      id: '/super'
      path: '/super'
      fullPath: '/super'
      preLoaderRoute: typeof SuperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super/': {
      id: '/super/'
      path: '/'
      fullPath: '/super/'
      preLoaderRoute: typeof SuperIndexRouteImport
      parentRoute: typeof SuperRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/super/stations': {
      id: '/super/stations'
      path: '/stations'
      fullPath: '/super/stations'
      preLoaderRoute: typeof SuperStationsRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/notifications': {
      id: '/super/notifications'
      path: '/notifications'
      fullPath: '/super/notifications'
      preLoaderRoute: typeof SuperNotificationsRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/insights': {
      id: '/super/insights'
      path: '/insights'
      fullPath: '/super/insights'
      preLoaderRoute: typeof SuperInsightsRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/chat': {
      id: '/super/chat'
      path: '/chat'
      fullPath: '/super/chat'
      preLoaderRoute: typeof SuperChatRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/broadcast': {
      id: '/super/broadcast'
      path: '/broadcast'
      fullPath: '/super/broadcast'
      preLoaderRoute: typeof SuperBroadcastRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/admins': {
      id: '/super/admins'
      path: '/admins'
      fullPath: '/super/admins'
      preLoaderRoute: typeof SuperAdminsRouteImport
      parentRoute: typeof SuperRoute
    }
    '/admin/station': {
      id: '/admin/station'
      path: '/station'
      fullPath: '/admin/station'
      preLoaderRoute: typeof AdminStationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/members': {
      id: '/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lockers': {
      id: '/admin/lockers'
      path: '/lockers'
      fullPath: '/admin/lockers'
      preLoaderRoute: typeof AdminLockersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/chat': {
      id: '/admin/chat'
      path: '/chat'
      fullPath: '/admin/chat'
      preLoaderRoute: typeof AdminChatRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminChatRoute: typeof AdminChatRoute
  AdminLockersRoute: typeof AdminLockersRoute
  AdminMembersRoute: typeof AdminMembersRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminStationRoute: typeof AdminStationRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminChatRoute: AdminChatRoute,
  AdminLockersRoute: AdminLockersRoute,
  AdminMembersRoute: AdminMembersRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminStationRoute: AdminStationRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface SuperRouteChildren {
  SuperAdminsRoute: typeof SuperAdminsRoute
  SuperBroadcastRoute: typeof SuperBroadcastRoute
  SuperChatRoute: typeof SuperChatRoute
  SuperInsightsRoute: typeof SuperInsightsRoute
  SuperNotificationsRoute: typeof SuperNotificationsRoute
  SuperStationsRoute: typeof SuperStationsRoute
  SuperIndexRoute: typeof SuperIndexRoute
}

const SuperRouteChildren: SuperRouteChildren = {
  SuperAdminsRoute: SuperAdminsRoute,
  SuperBroadcastRoute: SuperBroadcastRoute,
  SuperChatRoute: SuperChatRoute,
  SuperInsightsRoute: SuperInsightsRoute,
  SuperNotificationsRoute: SuperNotificationsRoute,
  SuperStationsRoute: SuperStationsRoute,
  SuperIndexRoute: SuperIndexRoute,
}

const SuperRouteWithChildren = SuperRoute._addFileChildren(SuperRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  SuperRoute: SuperRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
