name: Deploy Backend to Azure

on:
  push:
    branches:
      - feature/mobile_app
    paths:
      - 'smart_locker/backend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install Dependencies
        run: npm install
        working-directory: ./smart_locker/backend

      - name: Zip the app
        run: |
          cd ./smart_locker/backend
          zip -r ../../backend.zip .
          echo "--- Zip contents ---"
          unzip -l ../../backend.zip | grep "src/"

      - name: Deploy via ZipDeploy
        run: |
          curl -X POST \
            "https://smart-locker-backup-api-freycmg3g0b2dbcv.scm.eastasia-01.azurewebsites.net/api/zipdeploy" \
            -u "${{ secrets.AZURE_DEPLOY_USERNAME }}:${{ secrets.AZURE_DEPLOY_PASSWORD }}" \
            --data-binary @backend.zip \
            -H "Content-Type: application/zip"